const actions = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_BOOKING: 'NEW_BOOKING',
  NEW_CONTRACT: 'NEW_CONTRACT',
  SCAN_BOOKING: 'CONFIRM_BOOKING',
  SCAN_CONTRACT: 'CONFIRM_CONTRACT',
};

export default actions;
