const actions = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_BOOKING: 'NEW_BOOKING',
  NEW_CONTRACT: 'NEW_CONTRACT',
  UPDATE_CONTRACT: 'UPDATE_CONTRACT',
  SCAN_BOOKING: 'CONFIRM_BOOKING',
  SCAN_CONTRACT: 'CONFIRM_CONTRACT',
  REQUIRED_UPDATE_INFO: 'REQUIRED_UPDATE_INFO',
};

export default actions;
